version: '3.9'
services:
  parcels-app:
    build: .
    restart: always
    environment:
      POSTGRES_DSN: postgresql://postgres:password@db/postgres
      POSTGRES_SERVER: parcels-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - parcels-db
    ports:
      - "8080:8080"
    networks:
      - parcels

  parcels-db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5433:5432"
    restart: always
    networks:
      - parcels

networks:
  parcels:
    driver: bridge
